version: '3.7'

services:
  licensingservice:
    image: licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI: http://172.23.0.52:58071
    networks:
      backend:
        aliases:
          - "licenseservice"

networks:
  backend:
    driver: bridge

keycloak:
  image: jboss/keycloak
  restart: always
  environment:
    KEYCLOAK_USER: admin
    KEYCLOAK_PASSWORD: admin
  ports:
    - "8080:8080"
  networks:
    backend:
      aliases:
        - "keycloak"