spring:
  config:
    import: optional:configserver:http://localhost:8071
  application:
    name: licensing-service
  profiles:
    active: dev

management:
  health:
    diskspace:
      enabled: true
    db:
      enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
    health:
      enabled: true
      show-details: always