spring:
  config:
    import: optional:configserver:http://172.23.0.52:58071
  application:
    name: licensing-service
  profiles:
    active: dev

management:
  health:
    defaults:
      enabled: false
    diskspace:
      enabled: true
    db:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      enabled: true
      show-details: always

server:
  port: 8080